### ISSUE TITLE
Infinite loop in AwaitAsyncUpdateID function

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#10]
If I have well understood, we are stuck in an infinite loop, if for any reason, the status of the update is stuck to `enqueued`.

https://github.com/meilisearch/meilisearch-go/blob/f9427a2cc1e502de018a355ac65e4c81262e703e/client.go#L241-L256

We should define a default value of timeout.
This value could be change when passing an optional `timeOut` parameter in this function.

Plus, the name of the `updateID` parameter is not really accurate: the function expects an update "object" and not a updateID.

**Comment by alexisvisco** [comment]
Yes we can add a ctx for sure that let user define a timeout :)
That's a nice idea.
