### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by dev117uday** [meilisearch/meilisearch-go#104]
on the page of Quick start guide, in the create your index section, under the Go tab

[Quick Start Guide | Create your index](https://docs.meilisearch.com/guides/introduction/quick_start_guide.html#create-your-index)

in the third square box, the example given contains 
```
var client = NewClient(meilisearch/Config{
    Host: "http://127.0.0.1:7700",
})
```

it should be a `.` and not `/`

```
var client = NewClient(meilisearch.Config{
    Host: "http://127.0.0.1:7700",
})
```

**Comment by eskombro** [comment]
Well spotted, thanks!
