### ISSUE TITLE
Need synchronous API or at least give what's the sent request on /indexes/[table]/updates

### ISSUE THREAD

**Issue by kokizzu** [meilisearch/meilisearch-go#108]
Not printing the the requested json makes it harder to debug (I'm using go client btw)

already sent this:
```
"[{\"id\":20,\"author\":\"Prof. Laury Herzog\",\"title\":\"Aut perferendis accusantium sit voluptatem consequatur.\",\"body\":\"Consequatur accusantium voluptatem sit perferendis aut. Sit perferendis accusantium consequatur aut voluptatem. Perferendis accusantium aut sit voluptatem consequatur. Accusantium sit consequatur aut perferendis voluptatem. Sit accusantium aut perferendis consequatur voluptatem. Perferendis consequatur accusantium sit aut voluptatem. Perferendis sit voluptatem consequatur accusantium aut. Perferendis voluptatem sit aut consequatur accusantium. Voluptatem perferendis sit aut accusantium consequatur.\",\"created\":1606484683456729702}]"
```
but still got 
```
{"status":"failed","updateId":19,"type":{"name":"DocumentsAddition","number":1},"error":"document id is missing","errorType":"invalid_request_error","errorCode":"missing_document_id","errorLink":"https://docs.meilisearch.com/errors#missing_document_id","duration":0.000806693,"enqueuedAt":"2020-11-27T13:44:43.459032791Z","processedAt":"2020-11-27T13:44:43.462177939Z"}
```
apparently I was wrongly set the primary key in the past (because I was calling `.Documents(space).AddOrReplaceWithPrimaryKey(row, row.Id)`) -- because I thought the 3rd parameter is ID of that specific document instead of the primary key column name.
```
curl -X GET 'http://localhost:7700/indexes/articles'        
{"name":"articles","uid":"articles","createdAt":"2020-11-27T11:47:01.834279018Z","updatedAt":"2020-11-27T13:44:38.401930845Z","primaryKey":"5"}
```
so I have to drop it first..

**Comment by eskombro** [comment]
HEy @kokizzu 

So sad to see that you got blocked with this, but I am not sure of what is the solution you are actually proposing. Can you please make it a little bit more detailed?

Thanks!

**Comment by kokizzu** [comment]
either:
1. ability to replace `primaryKey` if there's no records yet
2. more detailed information about requested json string in the `/indexes/[table]/updates`
3. add synchronous API for `addOrReplace`

**Comment by eskombro** [comment]
1. If you have set a `primary key` and made an HTTP call to MeiliSearch, it won't be possible to update it. This is not something that can be handled at an SDK level, it's how the core of MeiliSearch works. Nonetheless, there are two things that come to mind:

- The latest MeiliSearch version introduces an `implicit index creation` feature that will modify the way SDK's are implemented (you can see for an [example of implementation](https://github.com/meilisearch/meilisearch-python/pull/171) the Python SDK) that will probably not make any HTTP call until you have indexed documents, meaning that this problem should be solved very soon.
- If you still think this should be handled differently by MeiliSearch core it is always possible to [open an issue in the core repository](https://github.com/meilisearch/MeiliSearch/issues/new/choose)

2. This is quite the same, SDK is meant to retrieve the information sent by the MeiliSearch server. What information is missing in your opinion?

3. There is the `waitForPendingUpdate` method that will let you handle your indexation in a synchronous way :)

**Comment by kokizzu** [comment]
ah not done yet ic..
![image](https://user-images.githubusercontent.com/1061610/100594239-01666f00-332c-11eb-9c0e-0aa67f421777.png)
https://github.com/meilisearch/integration-guides/issues/1

2. the information missing is the sent json, eg. 
if i send invalid json `[{"notThePrimaryKey":"foo","otherFields":"otherFieldValue"}]`, it should be there just for debugging reason

**Comment by eskombro** [comment]
If you are referring to `waitForPendingUpdate` method, it works pretty well, this issue means that there are no integration tests for it, and we would like to add some to make it reliable, but it has been used in several projects with the expected behavior, so it is totally available if you want to use it.

**Comment by kokizzu** [comment]
but there's no such method in https://github.com/meilisearch/meilisearch-go/blob/master/apis.go

**Comment by eskombro** [comment]
https://github.com/meilisearch/meilisearch-go/blob/8a213401a0c634e8f024fc824422601bc18ad430/client.go#L299

**Comment by curquiza** [comment]
Closing this issue then, feel free to re-open if needed.

**Comment by kokizzu** [comment]
or at least, the minimum, no need to wait indexing to complete, but return error if the input json is invalid
