### ISSUE TITLE
Typo In 'Add documents' Code Example In README.md File

### ISSUE THREAD

**Issue by umahmood** [meilisearch/meilisearch-go#14]
Hello,

The 'Add documents' code example in the README.md file contains a typo, which results in a compile error. The code:
```
var client = meilisearch.NewClient(meilisearch.Config{
        Host: "http://127.0.0.1:7700",
        APIKey: "masterKey"
    })
```
Is missing a comma at the end of "masterKey", example:
```
var client = meilisearch.NewClient(meilisearch.Config{
        Host: "http://127.0.0.1:7700",
        APIKey: "masterKey", // <- comma needed here :)
    })
```
Without the comma you get a compiler error:

`syntax error: unexpected newline, expecting comma or }`

Great project! 

Thanks.

**Comment by curquiza** [comment]
Hello!
Thanks a lot for your PR!
We really want to provide great examples in the README, so your issue is surely helpful. I fix that now!
