### ISSUE TITLE
A basic error handler

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-go#149]
Create a basic error handler, with these 3 custom errors:
- `MeiliSearchApiError`
- `MeiliSearchCommunicationError`
- `MeiliSearchTimeoutError`

MeiliSearch API has an error handler, and returns this kind of JSON when an error is found:

```json
{
  "message": "Index movies not found",
  "errorCode": "index_not_found",
  "errorType": "invalid_request_error",
  "errorLink": "https://docs.meilisearch.com/errors#index_not_found"
}
```
The complete list of errorCode is available in the [documentation](https://docs.meilisearch.com/errors)

It could be great to let the user access `message`, `errorCode`, `errorType` and `errorLink` to a better understanding an error.

**Comment by lewisreay** [comment]
👋 @alallema I can work on this if you want?

**Comment by alallema** [comment]
Hi @lewisreay !
Thanks a lot for this proposition. For now, I'm working on a big refactor of the code and I think this issue will probably be done internally.
However, don't worry there will be new issues available soon. Thanks again for your support.

**Comment by lewisreay** [comment]
No problem, thanks, @alallema! Looking forward to the new engine and refactor.

**Comment by curquiza** [comment]
@alallema, in the GetOrCreateIndex method, you must check the error is `index_not_found` once the error handler is implemented 😄
