### ISSUE TITLE
Wrong accepted status code on `/health` (Health() method)

### ISSUE THREAD

**Issue by fr3fou** [meilisearch/meilisearch-go#155]
**Description**
The `Health()` method expects an `HTTP 204 No Content` status code: 
![image](https://user-images.githubusercontent.com/1344906/122443835-9ff4ad80-cfa8-11eb-9e56-1b08aae29b8b.png)
This is not correct, as the docs state that it returns `HTTP 200 OK`:
![image](https://user-images.githubusercontent.com/1344906/122443920-b569d780-cfa8-11eb-9cf2-249be1edbc2c.png)

**Expected behavior**
I expect the `Health()` method to work as expected.

**Current behavior**
The function errors out, as the `/health` endpoint returns `HTTP 200 OK`
![image](https://user-images.githubusercontent.com/1344906/122444039-d16d7900-cfa8-11eb-8315-a8afe6a75720.png)

**Environment (please complete the following information):**
- OS: macOS 11.4
- MeiliSearch version: 0.20.0
- meilisearch-go version: v0.14.1

**Comment by alallema** [comment]
Hi @fr3fou!
You right thank for the report. We are currently working on a refactor where this issue is fixed.
I will linked your issue to the PR.
