### ISSUE TITLE
Fix local test

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#188]
Locally, the health test fails. We need to make it less precise to make it pass both on Linux and MacOs since the failure is not related to a dysfunctionality of the package neither of MeiliSearch

**Comment by mmachatschek** [comment]
@curquiza are we talking about e.g. the "no such host" DNS error that happens locally but not in CI for the test `TestClient_Health/TestHealthWithBadUrl`?

**Comment by curquiza** [comment]
Exactly! :)
