### ISSUE TITLE
Add a method to delete the index only if it already exists

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#202]
Trying to delete an index that does not exist on the MeiliSearch server will throw an error. To delete it without any error no matter what if it exists or not, we need a new method.

- [ ] Add a method `delete_index_if_exists`: it deletes the index but does not throw any error if the index does not exist.
- [ ] Add tests

Example: https://github.com/meilisearch/meilisearch-python/pull/268/files

⚠️ This issue is generated, and `delete_index_if_exists` might be named differently in this package. Keep the already existing way of naming in this package to stay idomatic with the language and the repository.

Related to https://github.com/meilisearch/integration-guides/issues/107

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue.

**Comment by kashifsoofi** [comment]
Can I take this please

**Comment by alallema** [comment]
Of course, I assigned you
