### ISSUE TITLE
Add method to get the raw index information

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#210]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/120

----

This SDK provides a method to get an index (`getIndex`) and this method returns an instance of `Index`. Some users want to get the raw version of the index, I mean the exact JSON response returned by the MeiliSearch server, not an instance.

Some SDKs already provide a way to get this raw index information but this is not convenient, example in PHP:

```php
$client->index('movies')->fetchRawInfo();
```

We need to add the `getRawIndex` method, accessible from the `Client` instance, to make it more convient.

Prototype:

```
getRawIndex(string indexUID) -> object/struct/dict of the MeiliSearch response
```

Ex in PHP:
```php
$client->getRawIndex('movies');
```

TODO:
- [ ] Add `getRawIndex()` method to the `Client` instance without duplicating the code (if `fetchRawInfo()` already exists for example)
- [ ] Add tests

**Comment by ratogabriel** [comment]
Hi, can I take that?

**Comment by Joel-Nickson** [comment]
Is there anything I could do to help?

**Comment by Joel-Nickson** [comment]
I was reading the docs and going through the code in go and other languages to understand the code a little deep for the last few days.
But reading the entire thing would be a waste of time for a minor upgrade.

So if someone could tell me which files to modify and what to add in them, it would save a lot of time of mine.

**Comment by alallema** [comment]
You don't have to run Meilisearch with docker if you are not comfortable with it. You can just download it and launch it [see](https://docs.meilisearch.com/learn/getting_started/installation.html#download-and-launch)
The tests should be passed you don't need permission. Tell me if it works better.
The difference between the `GetAllIndexes` and the  `GetAllRawIndexes` method is that the first one returns a list of [`Index`](https://github.com/meilisearch/meilisearch-go/blob/08be49c628de8cca31db0c5c63c37e19a145c187/types.go#L20) who is a struct use like a type and the second returns just a golang type `[]map[string]interface{}`.
