### ISSUE TITLE
Smaller batches cause some documents to be lost

### ISSUE THREAD

**Issue by misaelvillaverde** [meilisearch/meilisearch-go#214]
When I send in batches of 1000 concurrently, it seems to lost some of the documents in the process, but sending all the documents at once (for this example 3413) it doesn't lose any.

![image](https://user-images.githubusercontent.com/30275501/137328400-2f399b5c-232f-437d-9dea-c9cd9af15cf7.png)
## after (1000 by 1000):
![image](https://user-images.githubusercontent.com/30275501/137328667-e1bd06dd-cdd7-4dc0-a55b-de6fba520862.png)
![image](https://user-images.githubusercontent.com/30275501/137328768-5757e3a4-2353-4688-9e66-2fd50f2b850f.png)
## after (10 000):
![image](https://user-images.githubusercontent.com/30275501/137329417-76cdbb32-319e-4db8-8b79-aabddcdf48cf.png)
![image](https://user-images.githubusercontent.com/30275501/137329491-fea02c9a-1a2d-482b-8d21-78ddd5152501.png)

My code:
```go
	var wg sync.WaitGroup
	wg.Add(pages)

	fmt.Printf("%d pages of %d products each to do the load\n", pages, pageSize)
	pagesleft := pages

	// Load the products in parallel
	for i := 1; i <= pages; i++ {
		go func(i int, left *int) {
			defer wg.Done()

			fmt.Printf("Loading page %d, open connections: %d, connections in use: %d, idle connections: %d\n", i, conn.Stats().OpenConnections, conn.Stats().InUse, conn.Stats().Idle)
			start := time.Now()
			var unpackedProducts []Product

			// Get products from database
			log.Println("-------------------------------\nGetting products from page", i)

			products := db.GetProducts(conn, pageSize, i, load, true)
			e := json.Unmarshal([]byte(products), &unpackedProducts)
			if e != nil {
				log.Fatal(e)
			}

			if len(products) > 0 {
				update, err := index.AddDocuments(unpackedProducts)
				if err != nil {
					log.Printf("Meilisearch error on page %d:\n%s\n", i, err)
				} else {
					log.Println("Update:", update.UpdateID)
				}
			}
			fmt.Printf("-------------------------------\nPage %d done in %s, open connections: %d, connections in use: %d, idle connections: %d, products retrieved: %d\n", i, time.Since(start), conn.Stats().OpenConnections, conn.Stats().InUse, conn.Stats().Idle, len(unpackedProducts))

			// debug: documents to csv
			for _, product := range unpackedProducts {
				w.Write([]string{fmt.Sprint(i), product.ProductId, *product.ProductName})
			}

			unpackedProducts = nil

			*left -= 1
			fmt.Printf("%d pages left\n", *left)
		}(i, &pagesleft)
	}

	wg.Wait()

	log.Println("Done loading")
```

help 😔, I have a bigger index(130k), and I can't send one complete batch

**Comment by MisaelVillaverde** [comment]
Hi @alallema, thanks for your response
After loading the documents to a csv file, and analizing the data, it show that there are some repeated id's between batches, so the problem is in the cutting of my batches as you said in the second option, I'll be trying to figure out why it's happening, thank you and sorry for taking your time.

**Comment by alallema** [comment]
@MisaelVillaverde No problem. Good to know it is ok! Don't hesitate if you have any trouble.
