### ISSUE TITLE
Rename `MeilisearchApiMessage`?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#232]
@alallema shouldn't we renamed `MeilisearchApiMessage` into `MeilisearchApiError`?
Seems like `MeilisearchApiMessage` comes from the old MeiliSearch that only returned a message and nothing else
`MeilisearchApiMessage` now contains `message`, `link`, `type` and `code`.

**Comment by alallema** [comment]
Totally agree, I think that `MeilisearchApiMessage` is a relic from the old Meilisearch.
