### ISSUE TITLE
Server v0.24.0 breaks error deserialization

### ISSUE THREAD

**Issue by theag3nt** [meilisearch/meilisearch-go#240]
**Description**
The latest Meilisearch server version introduced breaking changes in the naming of fields in the error responses (meilisearch/MeiliSearch@61c15b69fb6dfd35676dd4008d29f27e9d2db35e) which also breaks the tests of this library. 

**Environment:**
- OS: Ubuntu/Docker
- MeiliSearch version: v0.24.0
- meilisearch-go version: 5248264288ab1cf40e0d9c0c1375cf81f522cb19

**Comment by alallema** [comment]
Hi @theag3nt,
You're right v0.24.0 has been released today 🎉 ! We are updating all the SDK.
[See](https://github.com/meilisearch/meilisearch-go/pull/229)

**Comment by alallema** [comment]
I closed this issue too #241
