### ISSUE TITLE
Fix the JSON unmarshaling for the /stats endpoint

### ISSUE THREAD

**Issue by roelofjan-elsinga** [meilisearch/meilisearch-go#249]
After Meilisearch v0.22.0 the /stats endpoint response changed from:

```json
{
    "database_size": 0,
    "last_update": null,
    "indexes": []
}
```

to:

```json
{
    "databaseSize": 0,
    "lastUpdate": null,
    "indexes": []
}
```

This hasn't been implemented in types.go yet, so these two fields cannot be parsed at the moment.

**Comment by alallema** [comment]
Thanks, @roelofjan-elsinga for raising and fixing this issue! 🔥
