### ISSUE TITLE
CreateIndex fails with 202 (Accepted) instead returning 201 (Created)

### ISSUE THREAD

**Issue by buergi** [meilisearch/meilisearch-go#252]
**Description**

    index, err := client.CreateIndex(&meilisearch.IndexConfig{
        Uid: "myindex",
        PrimaryKey: "myid",
      })

and therefore also GetOrCreateIndex. Throws an error on success.

**Expected behavior**
Should create a new index (assuming it doesn't already exist).

**Current behavior**
Returns the following error

    unaccepted status code found: 202 expected: [201], MeilisearchApiError Message:  (path "POST /indexes" with method "CreateIndex")

although status code 202 denotes success, and the index has been created afterwards.
I assume it has something to do with asynchronous creation. However, the behavior is unexpected.

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.3 LTS
- MeiliSearch version: v0.25.0
- meilisearch-go version: v0.17.0

**Comment by reolat** [comment]
Hello @buergi,
I had the same problem a few days ago. As far as I know, this is because this package is not yet compatible with MeiliSearch version `v0.25.0`. See [this PR](https://github.com/meilisearch/meilisearch-go/pull/247) for more details.

In the meantime you can use Meilisearch `v0.24.0`. :)

**Comment by brunoocasali** [comment]
Exactly @reolat :D 

@buergi we're still working to update all the integrations 😅.

Sorry for the inconvenience :/

**Comment by gf3** [comment]
@alallema @reolat @brunoocasali is there a temporary fix besides disabling authentication? i'm experiencing this issue on v0.24.0 (AWS images)
