### ISSUE TITLE
ApiKey not working for v0.25

### ISSUE THREAD

**Issue by reversTeam** [meilisearch/meilisearch-go#253]
**Description**
A modification took place on the method of authentication, this one does not work any more in version v0.25 can be before, I did not check.

Switching from `X-Meili-API-KEY: [...]` to `Authentication: Barrer [...]`
https://github.com/meilisearch/meilisearch-go/blob/main/client_request.go#L137

**Expected behavior**
The ApiKey must take into account the version of the client to work with the new and the old version.
The getVersion route is also protected by auth, you will either have to make it public, or give the definition in static from the client and create a new method to get the version of the remote.

**Current behavior**
We get an auth error on all requests when the configurations are correctly informed

**Screenshots or Logs**
Error Auth

**Environment (please complete the following information):**
- OS: OSX
- MeiliSearch version: V0.25
- meilisearch-go version: v16.6

**Comment by alallema** [comment]
Hi @reversTeam,
You are right this package it's not yet compatible. See more details on [this comment](https://github.com/meilisearch/meilisearch-go/issues/252#issuecomment-1018721156). Sorry for the inconvenience.
I will let closed this issue due to duplication with #252.
