### ISSUE TITLE
Why type waitParams is defined as a unexported type?

### ISSUE THREAD

**Issue by stormyyd** [meilisearch/meilisearch-go#270]
Hi, there!

I just wanna know why type `waitParams` is defined as a unexported type?

`WaitForTask` method was defined as:
```go
func WaitForTask(task *Task, options ...waitParams) (*Task, error)
```

Making type `waitParams` unexported will cause user cannot pass custom `options` parameter to this method.

I know I can use `WaitForTask` without options parameter, and for me it's ok. But I think maybe make `waitParams` become `WaitParams`, that is make it exported is better?

**Comment by alallema** [comment]
Hi @stormyyd,
Thanks for this comment. You're totally right it's a mistake!
