### ISSUE TITLE
WaitForTask 方法的可变参数没有提供公有声明

### ISSUE THREAD

**Issue by Juncheng-Hu** [meilisearch/meilisearch-go#273]
**Description**
![image](https://user-images.githubusercontent.com/33713644/156864162-da3e656b-354f-4dff-bc88-5756c5476074.png)

结构 waitParams 是私有的，无法在外部声明使用

**Basic example**
修改该结构为公有，或者提供初始化方法

**Comment by alallema** [comment]
Hi @Juncheng-Hu,
Thanks for raising this issue. You're right this was a mistake fixed by this #272 issue. I will try to release it soon. Sorry ...
