### ISSUE TITLE
Add support to the typo tolerance customization

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#288]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Related to:
- parent issue: https://github.com/meilisearch/integration-guides/issues/190
- specification: https://github.com/meilisearch/specifications/pull/117

----

Add a `typoTolerance` index settings resource to manage customization of the typo tolerance feature at the index level.

- Expose `typoTolerance` object on `/indexes/:index_uid/settings` endpoints.
- Add `GET/POST/DELETE` - `/indexes/:index_uid/settings/typo-tolerance` endpoints.

The `typoTolerance` object definition is made of the following properties:
  - `enabled` type (`boolean`)
  - `disableOnAttributes` type (`array[string]`)
  - `disableOnWords` type (`array[string]`)
  - `minWordSizeForTypos` type (`object`)
    - `oneTypo` type (`int`)
    - `twoTypos` type (`int`)

More information about what each field does could be [checked in the spec.](https://github.com/meilisearch/specifications/pull/117)

Check the other customization methods for reference like: `synonyms`, `searchableAttributes`, `filterableAttributes`.

TODO:
- [x] Add the new methods to customize `typo-tolerance`
  - [x] GET `/indexes/:index_uid/settings/typo-tolerance`
  - [x] POST `/indexes/:index_uid/settings/typo-tolerance`
  - [x] DELETE `/indexes/:index_uid/settings/typo-tolerance`
- [x] Add tests

**Comment by CatalinStratu** [comment]
Hello @brunoocasali, I'd like to handle this task. I think it's a good task for me to better understand the project.

**Comment by brunoocasali** [comment]
Awesome @CatalinStratu 🎉 

Since this typo customization is a new feature coming with the v0.27, and this package is not fully compatible yet with that version, to be possible to work on this issue, you should do this:

- Create a branch from `bump-meilisearch-v0.27.0` (and send your PR with this destination).
- Do your tests against Meilisearch v0.27.0rc1 and NOT `meilisearch:latest`. We have a few options for you to install it:
https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0rc1

And don't hesitate to ask if you have any doubt! 

Thanks for your help! ❤️

**Comment by alallema** [comment]
Hi @CatalinStratu,
Thank you for offering your help ❤️ . We are opening this issue in case we didn't have time to implement it during the pre-release. However, I had time to implement it. Feel to check it and do any comments!
