### ISSUE TITLE
Timeout error when trying to connect to a remote meilisearch index

### ISSUE THREAD

**Issue by vsumit89** [meilisearch/meilisearch-go#297]
<img width="1728" alt="Screenshot 2022-05-19 at 12 41 55 PM" src="https://user-images.githubusercontent.com/40121085/169232481-1f20d33b-6cde-4360-afe4-54f14aac0c07.png">

**Comment by alallema** [comment]
Hi @vsumit89,
Apparently, you are trying to do a `POST` search on port 8000 `http:/locahost:8000/search` but `Meilisearch` is accessible from the port `7700` maybe it could be from there.

**Comment by alallema** [comment]
Hi @vsumit89,
Did you find where your issue come from?

**Comment by alallema** [comment]
I close this issue due to inactivity for a long time.

**Comment by vsumit89** [comment]
Sorry @alallema 
I was inactive for a while. My issue has been solved, thanks for your help!
