### ISSUE TITLE
Typo in fasthttp client name

### ISSUE THREAD

**Issue by arnemolland** [meilisearch/meilisearch-go#298]
**Description**
The fasthttp client is initialized with the name "meilsearch". This sets the User-Agent header with the typo "meilsearch".

**Expected behavior**
User-Agent should be "meilisearch" not "meilsearch".

**Current behavior**
User-Agent is "meilsearch".

**Comment by alallema** [comment]
Hi @arnemolland,
Good catch thanks for raising this typo!
