### ISSUE TITLE
Find a better way to define `Limit` parameter in all `QueryParameter` structs

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-go#331]
**Description**
In all the methods that allow sending a query parameter as struct like:
- TasksQuery
- DocumentsQuery
- IndexesQuery
- KeysQuery
We check that the parameter limit exists:
```
    if param.Limit != 0 {
```
Yet, Meilisearch allows setting the limit parameter to 0, which is not possible currently with this SDK because the `Limit` is define as an `int64`
```
    Limit   int64   `json:"limit"`
```

The simple solution could be to define the `Limit` as an `*int` but in this case, it would force the user to initialize his struct in several lines such as:
```
    limit = 10
    query: &TasksQuery{
        Limit: *limit,
    }
```
instead of simply doing it as it is today:
```
    query: &TasksQuery{
        Limit: 10,
    }
```

It would be nice to find a solution that does not complicate the use for the user and allow at the same time to send the value 0

**Comment by aldy505** [comment]
Hi, I'd suggest a few things:

1. Use a builder pattern that's similar to Elasticsearch's client: `WithLimit(i int64)` -- this might break some API, or
2. Use the int64 pointer approach, but instead of having `*int64`, we could create a new `Limit` type that is a reference to `*int64`. The way the users should initialize it is through a function (like how you'd do it on AWS SDKs), `meilisearch.Limit(i int64)`
3. Set the limit to `< 0` for no limit on the query. To simplify things, we could create an exported variable: `meilisearch.NoLimit` (type of int64)

What do you think?

**Comment by aldy505** [comment]
1. Builder pattern:
```go
indexes, err := client.GetIndexes(meilisearch.WithLimit(10), meilisearch.WithOffset(0))

type IndexesQuery struct {
  parameter string
  value     string
}

func WithLimit(i int) IndexesQuery {
  return IndexesQuery{parameter: "limit", value: strconv.Itoa(i) }
}

// The same goes for WithOffset


// With GetIndexes being:
func (c *Client) GetIndexes(indexesQuery ...IndexesQuery) {
  requestParameters := url.URL{}

  for _, query := range indexesQuery {
    request
  }
  request, err := http.NewRequestWithContext(ctx, targetUrl, body)
  if err != nil { ... }


}
```

2. Pointer approach
```go
indexes, err := client.GetIndexes(meilisearch.IndexesQuery{Limit: meilisearch.Int(10), Offset: meilisearch.Int(0) })

type IndexesQuery struct {
  Limit: intPtr
  Offset: intPtr
}

type intPtr *int

// meilisearch.Int being:
func Int(i int) *intPtr {
  return &i
}
```

3. Less than zero limit - Create a global variable called NoLimit
```go
indexes, err := client.GetIndexes(meilisearch.IndexesQuery{Limit: meilisearch.NoLimit, Offset: 0})

var NoLimit = math.MinInt
```

**Comment by alallema** [comment]
Thank you so much @aldy505 for your really clear and well explain examples.
Sorry to have taken time to answer this message but I had a hard time choosing which solution I would prefer and especially the one that would bring less friction to the use. I think that my favorite is the Pointer approach.
I'm going to modify this issue in this sense

**Comment by Azanul** [comment]
@alallema @aldy505 Please checkout the PR, I went ahead with the pointer approach.

**Comment by aldy505** [comment]
Personally, I don't really recommend the pointer approach, as `nil` is an equivalent of `null pointer` like in C. It does not represent a `null` value like you'd see on Java, C#, or even Javascript.

It's also harder to use, as you would need to create a new variable that can't be reassigned if you as the user wants to modify the query even more. This happens a lot, especially if you're dealing with AWS' Go SDKs.

If we're after simplicity, I'd suggest the last option, create a global variable called `NoLimit` that represents the unlimited result the client may get. It's also easier to maintain and won't break any current API.

**Comment by Azanul** [comment]
> Personally, I don't really recommend the pointer approach, as `nil` is an equivalent of `null pointer` like in C. It does not represent a `null` value like you'd see on Java, C#, or even Javascript.

Where do you think this might cause an issue?

> It's also harder to use, as you would need to create a new variable that can't be reassigned if you as the user wants to modify the query even more. This happens a lot, especially if you're dealing with AWS' Go SDKs.

Not if user uses a simple helper function to convert the `int64` to `*int64`. Although it is indeed a bit repulsive.

> If we're after simplicity, I'd suggest the last option, create a global variable called `NoLimit` that represents the unlimited result the client may get. It's also easier to maintain and won't break any current API.

I agree with this idea of keeping it as `int64` only. But having 0 as default limit and user having to set no limit doesn't feel intuitive.

**Comment by aldy505** [comment]
> > Personally, I don't really recommend the pointer approach, as `nil` is an equivalent of `null pointer` like in C. It does not represent a `null` value like you'd see on Java, C#, or even Javascript.
> 
> Where do you think this might cause an issue?

Well it might not cause any issue if we code it thoughtfully and review every PR with care. But as an OSS project, there is no guarantee of that.

> > It's also harder to use, as you would need to create a new variable that can't be reassigned if you as the user wants to modify the query even more. This happens a lot, especially if you're dealing with AWS' Go SDKs.
> 
> Not if user uses a simple helper function to convert the `int64` to `*int64`. Although it is indeed a bit repulsive.

It's not just repulsive, it's also incompatible if we have our own `*int64` type. They have to create a variable first in order to query anything, which is the case with why some people don't like AWS' Go SDK.

```go
var limit *int64 = nil
limit = 12

indexes, err := GetIndexes(IndexesQuery{Limit: limit})
```

But with the last option, you could just do:

```go
indexes, err := GetIndexes(IndexesQuery{Limit: 12})

indexes, err := GetIndexes(IndexesQuery{Limit: meilisearch.NoLimit})
```

> > If we're after simplicity, I'd suggest the last option, create a global variable called `NoLimit` that represents the unlimited result the client may get. It's also easier to maintain and won't break any current API.
> 
> I agree with this idea of keeping it as `int64` only. But having 0 as default limit and user having to set no limit doesn't feel intuitive.

I stated earlier that the `meilisearch.NoLimit` equals to `math.MinInt`. Which is aligned with the requirements on the issue. The user are still allowed to put `0` as their parameters.

**Comment by Azanul** [comment]
> It's not just repulsive, it's also incompatible if we have our own *int64 type. They have to create a variable first in order to query anything, which is the case with why some people don't like AWS' Go SDK.

That variable is no neccesary. This is what I'm talking about.
```go
func int64p(int64 i) *int64 {
    return &i
}

indexes, err := GetIndexes(IndexesQuery{Limit: int64p(12)})
```

> I stated earlier that the meilisearch.NoLimit equals to math.MinInt. Which is aligned with the requirements on the issue. The user are still allowed to put 0 as their parameters.

The pointer approach keeps the consistency in use. Currently, default is no limit and user has to set a limit

**Comment by alallema** [comment]
Hi @Azanul,
I apologize for the delay. I took a little time because I wanted to be sure of my choice so that I don't make you rework unnecessarily. But after reading @aldy505's arguments I also think I prefer the `NoLimit` global variable option.

**Comment by alallema** [comment]
Due to the reduction of the maintenance on this repo and as this issue is not essential, I close it.
