### ISSUE TITLE
Get documents always give me zero value

### ISSUE THREAD

**Issue by jpastorm** [meilisearch/meilisearch-go#353]
**Description**
Hello, I am implementing the library and I see that a code function called GetDocuments is not working for me. I don't know why but others like search or GetDocument work for me. I don't see the error log, just a null message as if it had no data or something like that

**Expected behavior**
```
curl \
  -X GET 'http://localhost:7700/indexes/product/documents?limit=2'
{"results":[{"description":"un producto","id":1,"is_avaliable":true,"is_unlimited":true,"picture":"","pictures":[],"price":12.28,"product_category_id":1,"rated":0,"stock":1},{"description":"un producto","id":2,"is_avaliable":true,"is_unlimited":true,"picture":"","pictures":[],"price":12.28,"product_category_id":1,"rated":0,"stock":1}],"offset":0,"limit":2,"total":2}%     
```         

**Current behavior**
`null`
**Code**
```
var products []map[string]interface{}
	err := p.meilisearch.Index("product").GetDocuments(nil, &meilisearch.DocumentsResult{Limit: int64(limit), Offset: int64(offset), Results: products})
	if err != nil {
		return nil, fmt.Errorf("[GetProducts][%w]", err)
	}

	return products, nil
```
**Environment:**
- OS: Manjaro GNU/Linux
- Meilisearch version(docker image): getmeili/meilisearch:latest
- meilisearch-go version: v0.20.1

**Comment by alallema** [comment]
Hi @jpastorm,
You might have confused `DocumentQuery` with `DocumentResult`, I think your code should be something like :
```go
	var products []interface{}
	err := p.meilisearch.Index("product").GetDocuments(nil, &meilisearch.DocumentsQuery{Limit: int64(limit), Offset: int64(offset), &products})
	if err != nil {
		return nil, fmt.Errorf("[GetProducts][%w]", err)
	}
```

**Comment by jpastorm** [comment]
> 

Hi @alallema,

The function signature receives the structure DocumentResult :(.

`func (i Index) GetDocuments(request *DocumentsQuery, resp *DocumentsResult) error `

The day I tried it, it seemed strange to me that the struct has a DocumentResult because this struct does not have a pointer.

```
type DocumentsResult struct {
	Results []map[string]interface{} `json:"results"`
	Limit   int64                    `json:"limit"`
	Offset  int64                    `json:"offset"`
	Total   int64                    `json:"total"`
}
```

The struct doesn't receive a pointer so I can't pass a pointer to it.

**Comment by alallema** [comment]
Hi @jpastorm,
Yes I'm sorry it's not:
```go
	err := p.meilisearch.Index("product").GetDocuments(nil, &meilisearch.DocumentsQuery{Limit: int64(limit), Offset: int64(offset), &products})
```
but
```go
	err := p.meilisearch.Index("product").GetDocuments(&meilisearch.DocumentsQuery{Limit: int64(limit), Offset: int64(offset), &products})
```
The first one is used to send your query parameters and the second to receive your results.

**Comment by jpastorm** [comment]
Hello @alallema ,

The DocumentsResult struct is really needed because later in the code an unmarshal is made with the WithResponse attribute

`func (i Index) GetDocuments(request *DocumentsQuery, resp *DocumentsResult) error `
```
	req := internalRequest{
		endpoint:            "/indexes/" + i.UID + "/documents",
		method:              http.MethodGet,
		withRequest:         nil,
		withResponse:        resp,
		withQueryParams:     map[string]string{},
		acceptedStatusCodes: []int{http.StatusOK},
		functionName:        "GetDocuments",
	}
```

**Comment by alallema** [comment]
Yes, sorry I didn't re-write the variable it should be as you said a `DocumentResult{}` my code is exactly that:
```go
import (
	"fmt"

	"github.com/meilisearch/meilisearch-go"
)

	var movies meilisearch.DocumentsResult

	err := client.Index("movies").GetDocuments(&meilisearch.DocumentsQuery{Limit: int64(2), Offset: int64(0)}, &movies)
	if err != nil {
		fmt.Errorf("[GetMovies][%w]", err)
	}
	fmt.Println(movies)
```
It should normally works this way tell me if it still not the case

**Comment by jpastorm** [comment]
I forgot i could do that, it works
