### ISSUE TITLE
Updating settings returns 405 (Method not allowed)

### ISSUE THREAD

**Issue by RemiPail** [meilisearch/meilisearch-go#355]
**Description**
I would like to create a new index with specific settings.
I  used the code snippet from the [online documentation](https://docs.meilisearch.com/reference/api/settings.html#example-2)  

```golang
	meiliClient := meilisearch.NewClient(meilisearch.ClientConfig{
		Host:  ...,
		APIKey: ...,
	})

	settings := meilisearch.Settings{
                // new settings
	}

	_, err = meiliClient.Index("consents").UpdateSettings(&settings)
	if err != nil {
		fmt.Println(err)
                panic()
	}
```

**Expected behavior**
I expected no error happening
I expected the route GET /indexes/consents/settings to return the updated settings 

**Current behavior**
This code throws an error "405 Method not allowed" (screenshot below)
The route GET /indexes/consents/settings returns the default settings

I tried to call the route PATCH /indexes/consents/settings with Postman, the error is the same: "405 Method not allowed".
However, the route POST /indexes/consents/settings worked fine. 
**maybe the method PATCH is unsupported**

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/63208886/193049726-54b404a0-54d4-4824-8557-c3c304c545e7.png)

**Environment (please complete the following information):**
- OS: Linux
- Meilisearch version: v.0.27.2
- meilisearch-go version: v0.20.1

**Comment by alallema** [comment]
Hi @RemiPail,
You are right the `PATCH` method started to be used from the `v0.28.0` of `Meilisearch`. And from the version [v0.20.0](https://github.com/meilisearch/meilisearch-go/releases/tag/v0.20.0) of this SDK, it will only be compatible with the `v0.28.0`. So you can change your package version or upgrade to the `Meilisearch` version.
It should solve your issue
