### ISSUE TITLE
Get notification when a task succeed or failed?

### ISSUE THREAD

**Issue by kuchaguangjie** [meilisearch/meilisearch-go#357]
Currently I have to loop to retrieve task status, until it succeed or failed.
It there any way to get notified when a task succeed or failed, without loop, e.g via channel?

**Comment by kuchaguangjie** [comment]
Never mind, just found `client.WaitForTask()` method in the sdk.

**Comment by alallema** [comment]
Hi @kuchaguangjie,
Yes, this method exists mainly for tests but we do not recommend using it because it is blocking, so be careful with it.

**Comment by kuchaguangjie** [comment]
@alallema But, is there a better way to get notification ? Or, we don't need to.

**Comment by alallema** [comment]
Hi @kuchaguangjie,
Normally you should not need to be notified but I suggest that if you need it, it would be best to create a goroutine for this maybe. But in any case, you will have to make recurrent calls to the API who is not really good.
