### ISSUE TITLE
What's the best way to convert SearchResponse.Hits to []T?

### ISSUE THREAD

**Issue by kuchaguangjie** [meilisearch/meilisearch-go#362]
Each hit is a `map[string]any`, currently to convert `Hits` to `[]T` (e.g `[]model.Movie`), I have to loop each hit, and use json's marshal / unmarshal to convert it to T, I do that with a generic function as helper.

Do you have some better way to do that in current API.

If not, I might got some **suggestions:**
- Change all `[]interface` to `any`.
- Add generic support, at least some util functions.

**Comment by alallema** [comment]
Hi @kuchaguangjie,
Thanks for raising this issue, I think we already have one pretty similar to this issue #337. 
From my point of view, it would be a great addition to either create a utility function to this SDK to convert the `SearchResponse` return to an `[]T` or `[]interface{}` or to create a new function called `SearchRaw` for example that would directly return an `[]T` or `[]interface{}`.

**Comment by kuchaguangjie** [comment]
closed as duplicated with https://github.com/meilisearch/meilisearch-go/issues/337
