### ISSUE TITLE
Search parameters should be optional

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#4]
The search returns no result if I don't pass the `Limit` parameter. It does not fail. It just returns empty `Hits`.

```go
_, err := client.Search("indexUID").Search(meilisearch.SearchRequest{
	Query: "harry pottre",
})
```
=> no result

```go
_, err := client.Search("indexUID").Search(meilisearch.SearchRequest{
	Query: "harry pottre",
        Limit: 10,
})
```
=> result

We should be able to pass only the `Query` parameter

### Edit

<s>I understand that 2 parameters at least are needed because
```go
searchRes, err := client.Search("indexUID").Search(meilisearch.SearchRequest{
	Query: "harry pottre",
	AttributesToHighlight: "*",
})
```
returns results as well.</s>

My bad, it does not even run at all, I open an issue for that: #7 

### Version
`v0.9.0` of MeiliSearch.

**Comment by alexisvisco** [comment]
Hi thanks for your report: The default value of an int in Go is 0 so if you don't initialize the field `Limit` from the `SearchRequest` you get 0 result: it's normal.

Maybe we can provide a default limit in accordance to the MeiliSearch engine ?

**Comment by curquiza** [comment]
Hi!

The MeiliSearch engine uses a limit of 20 by default.

But isn't it possible to provide a function that sends a simple request without any parameter if the user does not provide any? 🙂 Except for the mandatory one (`query`) of course

**Comment by alexisvisco** [comment]
With the fix added in  `dev` it should be possible :)
