### ISSUE TITLE
Bit truncation on large 64bit ints

### ISSUE THREAD

**Issue by sam-ulrich1** [meilisearch/meilisearch-go#406]
**Describe the bug**
Meili is truncating large 64bit ints. I'm using the Go SDK so maybe it's there.
ex:  1613986188345999360 -> 1613986188345999400

**To Reproduce**
1. Enter the above number on the left in some document and query it

**Expected behavior**
Either note the max bit size in docs or not truncate

**Meilisearch version:** v0.30.0

**Comment by alallema** [comment]
Hi @sam-ulrich1,
Thanks or raising this issue.
>It because SearchResponse unmarshalls Hits into a []interface{}. Go assumes that the ints are 32 bit and truncate causing a rounding.

This is probably the case Go infers the numbers in `int` so in 32bits in {}interface. You can use the method `SearchRaw` which returns a `*json.RawMessage` and create your own type of `SearchResponse` until this bug is fixed.

**Comment by sam-ulrich1** [comment]
Ya, I just implemented a work around and decoded the data in a different fashion

**Comment by alallema** [comment]
Hi @sam-ulrich1,
I have tried on my side to reproduce your error, but I receive the correct data. I send this document:
```
    Hits: []interface{}{
        map[string]interface{}{
            "book_id": 1613986188345999360, "title": "Le Petit Prince",
        },
    },
```
Then print it, and print the `book_id`. I get the correct number.

![Screenshot 2023-01-23 at 19 26 49](https://user-images.githubusercontent.com/16155041/214120676-60809548-1078-4b62-b53a-8e800463a1b0.png)

Do you have an example of your issue that I could reproduce?

Thank

**Comment by sam-ulrich1** [comment]
I was able to reproduce modifying the test case to use int64 in the go SDK. I can share the code

**Comment by alallema** [comment]
> I was able to reproduce modifying the test case to use int64 in the go SDK. I can share the code
That would be great thanks 😊
