### ISSUE TITLE
Renamed `searchPostRequestParams` method

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-go#434]
**Description**
The method `searchPostRequestParams` transforms the structure containing all parameters to be sent to the API during a search into the correct format with the proper parameters.
It should be renamed more explicitly and better adapted to its function.

**Comment by Ja7ad** [comment]
`searchPostRequestParams` renamed to `SearchRequest` and currently support search with POST method.

https://github.com/meilisearch/meilisearch-go/blob/2ee420646adbfc34519d92930751b314d51ceb6e/types.go#L400-L432
