### ISSUE TITLE
Search response unmarshal issues

### ISSUE THREAD

**Issue by candiduslynx** [meilisearch/meilisearch-go#436]
**Description**

There are several issues with `SearchResponse` unmarshaling:
1. [These lines](https://github.com/meilisearch/meilisearch-go/blob/main/types_easyjson.go#L2138-L2147) are always defaulting to `in.Interface()` path per `v55` being nil interface
2. There's no way to properly unmarshal `uint64` value (`in.Interface()` -> `in.Float64()` that loses precision)

**Expected behavior**
1. `SearchResponse.Hits` unmarshaling should be addressed
2. It should be possible to unmarshal even the largest `uint64` value (`math.MaxUint64`)

**Current behavior**
1. `SearchResponse.Hits` always goes with `in.Interface()` path
2. `math.MaxUint64` value will lose precision per unmarshaling as `float64`

**Screenshots or Logs**

Stored value: `uint64(18446744073709551615)`
Scanned value: `float64(9223372036854775808)`

**Environment (please complete the following information):**
- OS: Linux
- Meilisearch version: v1.1.0
- meilisearch-go version: v0.24.0

**Comment by brunoocasali** [comment]
Hi @candiduslynx! 

The repo's maintainer, @alallema is on holiday. As soon as they get back, they will review your code! 

Thanks for the issue and the contribution!

**Comment by alallema** [comment]
Hi @candiduslynx,
Thanks for raising this issue. I will check that as soon as possible.

**Comment by alallema** [comment]
Sorry for the delay, It's the week of the engine release, so I'll take a look as soon as I can.
By the way it's seems to be related to this issue #406

**Comment by alallema** [comment]
> You use easyjson instead of standard encoding/json though.

Yes, indeed, but it should be utterly compatible with the `json` [library](https://github.com/tcolar/easyjson#marshallerunmarshaller-interfaces). You'd think we could handle the problem differently if we didn't use `easyjson`?

>It just corresponds to what is expected here, and in this case it's v55 discrepancy fixed:
>- either remove the type casting there
>- or assign something to v55 prior
>- or check not the v55 type but something else

Thanks for the details on the other topic, but the file you're talking about is auto-generated by `easyjson`. I'll have a look in their documentation to see if there are any options or ways to fix it.
If you have a suggestion for solving the problem, I'd love to hear it.

It's not always easy to manage typing for all cases, and some of the details in this SDK are not necessarily adequate. If you have any other feedback, please don't hesitate to contact us.

Thanks 😊

**Comment by sam-ulrich1** [comment]
Still a problem

**Comment by candiduslynx** [comment]
@alallema 
> I don't see how to change this, given

I think one of the things to be used here is actually something like https://pkg.go.dev/encoding/json#Decoder.UseNumber

Or https://github.com/tcolar/easyjson/blob/master/opt/gotemplate_Uint64.go

**Comment by candiduslynx** [comment]
@Ja7ad do you mind adding the PR with the fix to the issue?
Or was it intended to be closed as `won't fix`?

**Comment by Ja7ad** [comment]
> @Ja7ad do you mind adding the PR with the fix to the issue?
> Or was it intended to be closed as `won't fix`?

This issue is for easyjson and currently we don't have plans to fix it.

I think hits need a custom marshaller to fix the issue.

Please make a new issue for planning to fix this issue.

After high priority task v1.10.0 and v1.11.0.

I will fix it.


Please add more exception details in the new issue.

**Comment by Ja7ad** [comment]
@candiduslynx Please follow issue #579
