### ISSUE TITLE
Delete documents only using primary keys, not conditional filtering

### ISSUE THREAD

**Issue by freddiela** [meilisearch/meilisearch-go#438]
rt～

**Comment by freddiela** [comment]
Only primary keys can be used to delete documents. Conditional filtering is not supported

**Comment by freddiela** [comment]
Good afternoon.  @alallema 

my doc: {"id":1,"flag":1,"content":"hey~"} 
primary-key:id

When I delete doc with meilisearch-go, I can only delete it with the primary key, but I want to delete it with flag=1.
Example: "delete from doc where flag=1"

I'm sorry for my poor english. I'm not sure you understand this😂😂😂😂

**Comment by freddiela** [comment]
I was just wondering how to use meilisearch-go to delete documents without using primary keys
just like this :    delete from users where age=1 and sex=2

**Comment by alallema** [comment]
This [feature](https://github.com/meilisearch/specifications/pull/236) will not be available before the release of Meilisearch v1.2 I let you consult the [documentation](https://www.meilisearch.com/docs/reference/api/documents#delete-documents-by-batch) for more information.
If you have any questions about the use of Meilisearch, don't hesitate to join our [discord](https://discord.gg/meilisearch).
