### ISSUE TITLE
Is it possible to get the exact number of records?

### ISSUE THREAD

**Issue by atanassia** [meilisearch/meilisearch-go#443]
I know that there is an "estimatedTotalHits" parameter, but it shows the wrong value, sometimes even twice as much, so how can I get the exact number of rows in this case? Or if it is not possible, are there alternatives, the exact number of lines is needed for pagination.

**Comment by oluademola** [comment]
Hello @atanassia. It is possible to get the exact number of search results by using the `hitsPerPage` parameter in your search query. You can find more information in this [guide](https://www.meilisearch.com/docs/reference/api/search#exhaustive-and-estimated-total-number-of-search-results)

**Comment by alallema** [comment]
Thanks @oluademola, as the question has been answered I'm closing this issue.
