### ISSUE TITLE
Support updating the primary key of an index to `nil`

### ISSUE THREAD

**Issue by Mandrenkov** [meilisearch/meilisearch-go#449]
**Description**
To my best knowledge, it is not currently possible to update the primary key of an index to `nil`. Sure, you can _create_ an index with a `nil` primary key, but if you change the primary key to some string, there is no way to _update_ it back to `nil`.

**Basic example**

Ideally, it would be possible to write either
```go
index.UpdateIndex("")
```
or
```go
index.UpdateIndex(nil)
```
to update the primary key of `index` to `nil`.

**Other**

I'm no expert in Go or Meilisearch, but it looks like this might be the case because
```go
type UpdateIndexRequest struct {
	PrimaryKey string `json:"primaryKey"`
}
```
is not annotated with `omitempty` as in
```go
type UpdateIndexRequest struct {
	PrimaryKey string `json:"primaryKey,omitempty"`
}
```
and thus the server always receives `""` instead of `null`.

**Comment by oluademola** [comment]
Hello @Mandrenkov. I am sorry I don't understand your use case and why you want to set the primary key as nil, but I am curious about what happened. I don't have much context, so could you please provide more details? Specifically, what happens when you try to update the primary key? Do you receive an error message? Also, do you have documents in the index? What is your use case?

**Comment by Mandrenkov** [comment]
Hi @oluademola,

> I am sorry I don't understand your use case and why you want to set the primary key as nil, but I am curious about what happened. I don't have much context, so could you please provide more details?

Sure! For some context, I'm looking into developing a [Terraform](https://www.terraform.io/) provider for Meilisearch in order to manage Meilisearch indices using configuration files (as opposed to manual API calls or scripts). For example, I can configure a Meilisearch index using code which looks like this:
```terraform
resource "meilisearch_index" "foo" {
    uid         = "foo"
    primary_key = "bar"

    settings = {
        stop_words = ["some", "stop", "words"]
    }
}
```

To do so, I'm using the Meilisearch Go library to perform CRUD operations on Meilisearch indices. For example, if I define a Meilisearch index using

```terraform
resource "meilisearch_index" "foo" {
    uid = "foo"
}
```

I can create the index using [`CreateIndex(&IndexConfig{Uid: "foo"})`](https://pkg.go.dev/github.com/meilisearch/meilisearch-go@v0.25.0#Client.CreateIndex) and the primary key is set to `null` as expected. If I then decide to set another primary key as in

```terraform
resource "meilisearch_index" "foo" {
    uid         = "foo"
    primary_key = "bar"
}
```

I can simply call [`UpdateIndex("bar")`](https://pkg.go.dev/github.com/meilisearch/meilisearch-go@v0.25.0#Index.UpdateIndex)  and the primary key is set to `bar`. So far, so good! But now, if I change my mind and decide I'm not sure what the primary key should be and go back to

```terraform
resource "meilisearch_index" "foo" {
    uid = "foo"
}
```

there is no way, using the Meilisearch Go library, to set the primary key back to `null`!

> Specifically, what happens when you try to update the primary key? Do you receive an error message?

Well, the issue is that there is no way to update the primary key to `null`. If I try to use something like
```go
index.UpdateIndex("")
```
the primary key is set to `""` (instead of `null`). Of course, trying to call
```go
index.UpdateIndex(nil)
```
directly results in a type error as `string` values cannot be `nil`.

> Also, do you have documents in the index? What is your use case?

I don't have any documents in the index. My use case is configuring the index before uploading documents to it.

---

Perhaps it would help if I phrased this issue another way. Suppose that you have an index, with UID `foo`, with a primary key set to `bar`. After looking into the requirements some more, you realize you can't predict the primary key ahead of time and would like [Meilisearch to guess it](https://www.meilisearch.com/docs/learn/core_concepts/primary_key#meilisearch-guesses-your-primary-key). Unfortunately, there is no way you can update the primary key to be `nil` now and so your only course of action is to delete index `foo` and then recreate it with a `null` primary key!

**Comment by oluademola** [comment]
Hello @Mandrenkov. Thank you very much for the detailed and clear explanation. You are correct in stating that the only solution, in this case, is to recreate the index. It applies when using the API as well, as it's currently impossible to reset an index's primary key to its default value of null. This could be considered a limitation or a feature request. I encourage you to share this information and more details about your use case by starting a discussion in the [product repository](https://github.com/meilisearch/product/discussions/). Thank you in advance 🙏

**Comment by Mandrenkov** [comment]
> It applies when using the API as well, as it's currently impossible to reset an index's primary key to its default value of null. 

Ah, from the [Meilisearch API docs](https://www.meilisearch.com/docs/reference/api/indexes#update-an-index) I thought it was possible to use something like
```console
$ curl \
  -X PATCH 'http://localhost:7700/indexes/movies' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "primaryKey": null }'
```
to set the primary key to `null` but that just sets the primary key to `"null"` instead. 🤦 

> I encourage you to share this information and more details about your use case by starting a discussion in the [product repository](https://github.com/meilisearch/product/discussions/). Thank you in advance 🙏

Sure, I can do that when I get the chance!

**Comment by Mandrenkov** [comment]
Hey @oluademola, I came across a related issue with updating the typo tolerance of an index _which_ does seem to be a bug in the Meilisearch Go library. Specifically, I can't find a way to disable typo tolerance in an index.

I think the culrpit is similar to the one at the top of this issue, namely that `Enabled` is marked with  `omitempty`:

```go
// TypoTolerance is the type that represents the typo tolerance setting in Meilisearch
type TypoTolerance struct {
	Enabled             bool                `json:"enabled,omitempty"`
	MinWordSizeForTypos MinWordSizeForTypos `json:"minWordSizeForTypos,omitempty"`
	DisableOnWords      []string            `json:"disableOnWords,omitempty"`
	DisableOnAttributes []string            `json:"disableOnAttributes,omitempty"`
}
```

This is especially problematic as typo tolerance is enabled by default in Meilisearch indexes. As a result, I don't think it's possible for a Meilisearch index, managed using the Meilisearch Go library, to have typo tolerance disabled.

Note that it is possible to disable typo tolerance using a raw HTTP request like so:
```bash
curl \
  -X PATCH 'http://localhost:7700/indexes/books/settings/typo-tolerance' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "enabled": false
  }'
```

**Comment by alallema** [comment]
Hi @Mandrenkov,
Thanks for raising this issue!
I invite you to open a new issue for this problem to have an adequate follow-up of the problems reported in this repo especially if it's a bug. This will also allow us to close this one.

**Comment by Mandrenkov** [comment]
Thanks @alallema, I've opened #452 to capture the follow-up issue.

**Comment by macraig** [comment]
Hi @Mandrenkov , Meilisearch product team here! 👋 Your feature request is interesting and could be helpful to other users, so I'll close this issue and move this conversation to our Product repo for better tracking. 

We'll keep this discussion open, allowing others who might be facing similar challenges to jump in and share their thoughts :)

**Comment by macraig** [comment]
Closing in favor of https://github.com/meilisearch/product/discussions/682
