### ISSUE TITLE
Allow typo tolerance to be disabled for an index

### ISSUE THREAD

**Issue by Mandrenkov** [meilisearch/meilisearch-go#452]
**Description**
To my best knowledge, it is impossible to disable the typo tolerance of an index. This is due to two factors:
1. An index is always created with typo tolerance enabled.
2. An index cannot be updated to disable typo tolerance because setting `TypoTolerance.Enabled` to `false` causes the `Enabled` field to be omitted during JSON serialization due to the `omitempty` annotation:
```go
// TypoTolerance is the type that represents the typo tolerance setting in Meilisearch
type TypoTolerance struct {
    Enabled             bool                `json:"enabled,omitempty"`
    MinWordSizeForTypos MinWordSizeForTypos `json:"minWordSizeForTypos,omitempty"`
    DisableOnWords      []string            `json:"disableOnWords,omitempty"`
    DisableOnAttributes []string            `json:"disableOnAttributes,omitempty"`
}
```

**Basic example**

Suppose there exists a configured Meilisearch client:
```go
var client *meilisearch.Client
```

We can create an index as follows:
```go
indexConfig := &meilisearch.IndexConfig{Uid: "foo"}

task, err := client.CreateIndex(indexConfig)
if err != nil {
    panic(err)
}

if _, err = client.WaitForTask(task.TaskUID); err != nil {
    panic(err)
}
```

So far, so good! We can see that typo tolerance is enabled by default:
```go
index, err := client.GetIndex(task.IndexUID)
if err != nil {
    panic(err)
}

settings, err := index.GetSettings()
if err != nil {
    panic(err)
}

fmt.Printf("%v\n", settings.TypoTolerance.Enabled)  // true
```

The problem happens when we try to disable typo tolerance using [`Index.UpdateTypoTolerance()`](https://pkg.go.dev/github.com/meilisearch/meilisearch-go#Index.UpdateTypoTolerance):
```go
typoTolerance := &meilisearch.TypoTolerance{Enabled: false}

task, err = index.UpdateTypoTolerance(typoTolerance)
if err != nil {
    panic(err)
}

if _, err = client.WaitForTask(task.TaskUID); err != nil {
    panic(err)
}
```

If we retrieve the settings again, we can see that typo tolerance is still enabled:

```go
settings, err = index.GetSettings()
if err != nil {
    panic(err)
}

fmt.Printf("%v\n", settings.TypoTolerance.Enabled)  // true (instead of false)
```

**Other**

It is worth noting that this issue is not specific to `TypoTolerance.Enabled`. It is impossible, for similar reasons, to set `TypoTolerance.DisableOnWords` to `[]string{}` after it has been set to a different value:

```go
// First, set TypoTolerance.DisableOnWords to some non-zero value.

typoTolerance := &meilisearch.TypoTolerance{DisableOnWords: []string{"bar"}}

task, err = index.UpdateTypoTolerance(typoTolerance)
if err != nil {
    panic(err)
}

if _, err = client.WaitForTask(task.TaskUID); err != nil {
    panic(err)
}

settings, err = index.GetSettings()
if err != nil {
    panic(err)
}

fmt.Printf("%v\n", settings.TypoTolerance.DisableOnWords) // [bar]

// Now, try to set TypoTolerance.DisableOnWords to the empty slice.

typoTolerance = &meilisearch.TypoTolerance{DisableOnWords: []string{}}

task, err = index.UpdateTypoTolerance(typoTolerance)
if err != nil {
    panic(err)
}

if _, err = client.WaitForTask(task.TaskUID); err != nil {
    panic(err)
}

settings, err = index.GetSettings()
if err != nil {
    panic(err)
}

fmt.Printf("%v\n", settings.TypoTolerance.DisableOnWords) // [bar] (instead of [])
```

**Comment by alallema** [comment]
Hi @Mandrenkov,

Thank you for raising this issue 🚀 

You're absolutely right, this may not have been the best implementation choice and it makes it impossible to set specific attributes to false.
But I didn't want the user to have to set all the values when using the methods. One way to solve this problem is to remove `omitempty` and either force the user to set enabled or have a default value of true.

Unfortunately, we're a bit busy at the moment and I don't think we'll be able to solve this problem for some time yet.
PR is always welcome, so I'm putting this issue in good first issue 😊
