### ISSUE TITLE
What's the meaning of getting a pointer again? Don't understand

### ISSUE THREAD

**Issue by lee157953** [meilisearch/meilisearch-go#454]
![图片](https://github.com/meilisearch/meilisearch-go/assets/30332409/71974b9e-53c4-42c2-bb1d-23b4ba8ca7d8)

**Comment by alallema** [comment]
Hello @lee157953,
I'm not sure to understand your issue. If you want to improve the meilisearch-go SDK, PR is always welcome :slightly_smiling_face:

**Comment by alallema** [comment]
Without further details and return on this issue I close it.
