### ISSUE TITLE
API doesn't take context.Context

### ISSUE THREAD

**Issue by Hades32** [meilisearch/meilisearch-go#462]
every network operation in Go should take a context, so it can be cancelled and proper deadlines applied. This is only available in the task waiting api and even there in a non-standard manner

**Comment by brunoocasali** [comment]
Hi @Hades32, how are you?

I'm sure your right, and this is indeed a good refactor! But we will not have the time and human resources to make those changes. 

Will you or someone watching this issue be able to implement it?

**Comment by ysyneu** [comment]
@brunoocasali @Hades32 Hi, how are you? I do not think it is easy to do this. The api call use the fasthttp library, which do not accept a context param. Do you have any better ideas?

**Comment by curquiza** [comment]
Hello @ysyneu
I discussed with @brunoocasali but we don't have any better idea. We think the topic of the issue is still valuable despite it's not easy to do it as you said.

Any help of the community is welcome here ❤️

**Comment by Ja7ad** [comment]
fasthttp used `sync.Pool` for request and response objects for improved memory and performance.

Doesn't support outer context for request cancelation.

**Comment by zeisss** [comment]
Are there actual hard requirements for using `fasthttp`? I could see "abstracting" away the actual http client and having the default http client (with supported cancelation and other standard transport shenanigans people want) and fasthttp (no cancelation) as options.
