### ISSUE TITLE
Update to a version with AttributesToSearchOn

### ISSUE THREAD

**Issue by konstantin83** [meilisearch/meilisearch-go#464]
Hey. How to update local package to have a `AttributesToSearchOn` attribute from v1.3? It's on the github, but locally updating with `go get -u` doesn't pull this latest release. Maybe you didn't change the version tag?

**Comment by brunoocasali** [comment]
Hi @konstantin83 this request is being tracked here: https://github.com/meilisearch/meilisearch-go/issues/466

Unfortunately, we don't have enough free time to implement it, so feel free to tackle that issue, I'm here to help if you need anything!
