### ISSUE TITLE
[v1.3] Define fields to search on at search-time (`attributesToSearchOn`)

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#466]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

This issue is divided into two sections, first, you need to make the implementation, and second, you must update the code-samples (no one likes outdated docs, right?).

### New implementation

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3772
- discussion: https://github.com/meilisearch/product/discussions/107#discussioncomment-6184044
- spec: https://github.com/meilisearch/specifications/pull/251

Add support for receiving a new key, `attributesToSearchOn ` (an array of field names), to enable running searches over a subset of `searchableAttributes` without modifying Meilisearch’s index settings.

### Code samples

Inside of this file: `.code-samples.meilisearch.yml`:

1. Create a new entry with this key `search_parameter_guide_attributes_to_search_on_1` containing a call to the `search` method using the new behavior.
Refer to this curl example, and "translate" it by using go methods: https://github.com/meilisearch/documentation/blob/e4fdc3d485c22e31a045b8a71bacf18b6a7d50e0/.code-samples.meilisearch.yaml#L1103

TODO:
- [ ] Add the ability to receive a new param in the `search` method called `attributesToSearchOn`.
- [ ] Add integration tests
- [ ] Update the code-samples accordingly

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch-go/pull/458
and https://github.com/meilisearch/meilisearch-go/pull/493
