### ISSUE TITLE
[v1.3] Display hits ranking scores

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#467]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

This issue is divided into two sections, first, you need to make the implementation, and second, you must update the code-samples (no one likes outdated docs, right?).

### New implementation

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3771
- discussion: https://github.com/meilisearch/product/discussions/594 
- spec: https://github.com/meilisearch/specifications/pull/252

This feature aims to return ranking details for each document to understand and tweak the score of the documents more efficiently.

Ensure the SDKs can handle the new search parameter `showRankingScore`. Also, ensure the SDK can handle the `_rankingScore` attribute in the matched `hits`.

### Code samples

Inside of this file: `.code-samples.meilisearch.yml`:

1. Create a new entry with this key `search_parameter_guide_show_ranking_score_1` containing a call to the `search` method using the new behavior from the index `movies` using `showRankingScore=true` and a `q` with `'dragon'`.
Add a new code sample to the `.code-samples.meilisearch.yml` file:

Use this as a reference _if the previous description was not helpful_:

```
search_parameter_guide_show_ranking_score_1: |-
  POST 'http://localhost:7700/indexes/movies/search' 
  with data: { 
    "q": "dragon", "showRankingScore": true
  }
```

TODO:
- [ ] Add the ability receive a new param in the `search` method called `showRankingScore`.
- [ ] Add the ability handle the new `_rankingScore` key/value in the search hits' response.
- [ ] Update the code-samples accordingly
- [ ] Add integration tests

**Comment by 201RichK** [comment]
Hi ✋🏻 Is this issue still available? I'd like to take it.

**Comment by curquiza** [comment]
Hello @201RichK

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by brunoocasali** [comment]
Hi @201RichK yes! you can take it :)
