### ISSUE TITLE
[v1.3] [EXPERIMENTAL] Display ranking details at search

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#468]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

This issue is divided into two sections, first, you need to make the implementation, and second, you must update the code-samples (no one likes outdated docs, right?).

### New implementation

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3771
- spec: https://github.com/meilisearch/specifications/pull/252

This feature aims to return ranking details for each document to understand and tweak the score of the documents more easily.

Ensure the SDKs can handle the new search parameter `showRankingScoreDetails`. Also ensure the SDK can handle the `_rankingScoreDetails` attributes in the matched `hits`.

:warning: This feature is enabled by querying `PATCH /experimental-features` with `{ "scoreDetails": true }`

**Extra:** Add inline documentation for the method, explaining the availability of this feature only for Meilisearch v1.3 and newer. And that is also an experimental feature that must be manually opt-in using the `/experimental-features` https://github.com/meilisearch/meilisearch/issues/3857 endpoint.

TODO:
- [ ] Add the ability receive a new param in the `search` method called `showRankingScoreDetails`.
- [ ] Add the ability handle the new `_rankingScoreDetails` key/value in the search hits' response.
- [ ] Add integration tests (don't forget to enable the experimental feature)

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/meilisearch-go/issues/518 because the feature has been stabilized in Meilisearch v1.7
