### ISSUE TITLE
[v1.3] Total Tasks in task route

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#471]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

### New implementation

Related to:
- spec: https://github.com/meilisearch/specifications/pull/253

Returns the total number of tasks matching the filters on the `GET /tasks` route.

Ensure the SDKs can handle the new get tasks response field `total`

TODO:
- [ ] Handle the response of the `getTasks` method by including the new attribute `total`

**Comment by tonyghouse** [comment]
Raised a PR for this issue https://github.com/meilisearch/meilisearch-go/pull/475. can you check once?

**Comment by brunoocasali** [comment]
Closed by #475
