### ISSUE TITLE
Ensure the error handling are following the best practice

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#473]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/267

----

:warning: For more information check https://github.com/meilisearch/integration-guides/issues/267

Ensure this SDK follows the following guidelines:

- All the errors > 400 without message should be sent as `MeilisearchCommunicationError`
- Know errors like index is not found, or mistakes in the request like not-allowed params should be sent as `MeilisearchApiError`
- Any other error should be a `MeilisearchError` 

Essentially all the error should extend from `MeilisearchError`, the consumers should have a way to catch all the errors.
Let us know if this is not clear, or you have better idea!

TODO:
- [x] Create a base error called `MeilisearchError` which will extend the standard error if it does not exist (when the language supports)
 - [x] Make all the other errors extend this error.
- [x] Move all errors without message to `MeilisearchCommunicationError` since it is not a Meilisearch error anyway.

**Comment by heysujal** [comment]
Hi @brunoocasali, I am new to this project and would like to work on this one. I recently learnt go basics, so I think this would be a good issue for me.

**Comment by heysujal** [comment]
@brunoocasali can you assign me this please.

**Comment by brunoocasali** [comment]
Hi @heysujal 

We prefer not assigning external people to our issues.
Because people often ask to be assigned and never return, which discourages other potential contributions.
We will accept and merge the first PR that fixes correctly and implements the issue.

**Comment by heysujal** [comment]
> Hi @heysujal
> 
> We prefer not assigning external people to our issues. Because people often ask to be assigned and never return, which discourages other potential contributions. We will accept and merge the first PR that fixes correctly and implements the issue.

Understood

**Comment by heysujal** [comment]
Hi, I have not been able to figure it out like how to go about doing this.

**Comment by Ja7ad** [comment]
@brunoocasali I reviewed the error handling. The current implementation aligns well with common best practices, including structured error handling, contextual error messages, and integration with API-specific errors.

However, there is room for improvement in the future.

**Comment by curquiza** [comment]
Thank you @Ja7ad 
Is it ok for you @Ja7ad to close this issue and open new one more specific with the "room for improvements" you mention? Or do you think we don't need to open an issue yet? or should we let this current issue open?

**Comment by Ja7ad** [comment]
> Thank you @Ja7ad 
> Is it ok for you @Ja7ad to close this issue and open new one more specific with the "room for improvements" you mention? Or do you think we don't need to open an issue yet? or should we let this current issue open?

I think it's okay.

**Comment by curquiza** [comment]
Ok, so I close the issue ✅ feel free to open an new one with future improvements
