### ISSUE TITLE
UpdateDocumentsInBatches is actually invoking saveDocumentsInBatches

### ISSUE THREAD

**Issue by yanyandenuonuo** [meilisearch/meilisearch-go#509]
**Description**
When i want to update documents in batch, i used the method `UpdateDocumentsInBatches`, but there were a lot of tasks failed, then i found the method invoked `saveDocumentsInBatches`, just same as `AddDocumentsInBatches`.

**Expected behavior**
Implement real `UpdateDocumentsInBatches` or delete the method.

**Current behavior**
Execute as **Add** not **Update**

**Environment (please complete the following information):**
- OS: [Linux]
- Meilisearch version: [v.1.6.0]
- meilisearch-go version: [v0.26.1]

**Comment by curquiza** [comment]
Thank you for the report @yanyandenuonuo 

Any contribution are welcome 😊

**Comment by migueltarga** [comment]
This report is invalid. Both methods, `AddDocumentsInBatches` and `UpdateDocumentsInBatches`, use the same method, `saveDocumentsInBatches`, to adhere to the DRY principle while maintaining correct behavior. It was introduced here: https://github.com/meilisearch/meilisearch-go/commit/e7450c484ec2c917548c1e5716a03cbbc2643157.

@curquiza, this issue should be closed.

**Comment by curquiza** [comment]
Thank you @migueltarga for your help here
I close

Feel free to ask to re-open if we miss understood something
