### ISSUE TITLE
WaitForTask leaking CPU usage

### ISSUE THREAD

**Issue by thisisdev-patrick** [meilisearch/meilisearch-go#522]
**Description**
WaitForTask using CPU when Idle (simulation included)

**Expected behavior**
0 % CPU 

**Current behavior**
4000 Calls to WaitForTask causing 10-15% CPU usage

**Screenshots or Logs**
Arch:
![image](https://github.com/meilisearch/meilisearch-go/assets/5593142/c6511fa2-3bba-434f-aad8-91849e6740ce)
MacOS:
![image](https://github.com/meilisearch/meilisearch-go/assets/5593142/f95a5bd9-4bbf-44b6-9592-7140afeae854)

**Environment (please complete the following information):**
- OS: Tested on Arch kernel 6.8.1 and MacOS 14.4(M2)
- Meilisearch version: v.1.7.5
- meilisearch-go version: v0.26.2

Simulation code:

https://gist.github.com/thisisdev-patrick/da24fb4757820c611e2ea696d2e93953

**Comment by curquiza** [comment]
Hello @thisisdev-patrick 
thanks for the report


Any PRs are welcome to help on this 🙏

**Comment by thisisdev-patrick** [comment]
working on it
