### ISSUE TITLE
Get Total Number of hits for SearchResponse

### ISSUE THREAD

**Issue by HelmutLety** [meilisearch/meilisearch-go#53]
We don't get the Total Size of the Search Response, but we do get it as `nbHits` in the web-interface.
To fix that, could we add  :
_TotalHits    int64   `json:"nbHits"`_  to the struct `SearchResponse` in types.go?

**Comment by eskombro** [comment]
Thanks @HelmutLety for your creating this issue, indeed, the `nbHits` sent in the MeiliSearch response for search was not included in the SearchResponse struct, so it is being ignored when the json gets unmarshalled. I'll make a quick fix for this!

**Comment by eskombro** [comment]
This should be fixed now @HelmutLety, thanks and let us know if you have any other issue :)

**Comment by HelmutLety** [comment]
Thank you for the fast fix :)
