### ISSUE TITLE
Omitting `Hybrid.Embedder` selects `""` not `"default"`

### ISSUE THREAD

**Issue by yuku** [meilisearch/meilisearch-go#536]
**Description**
https://github.com/meilisearch/meilisearch-go/blob/0131c589e0fe9a02510dddb1f74b42ec34a45837/index_search.go#L150-L155

Due to L152, `""` will be send to the API if `request.Hybrid.Embedder` is `""`, which is the zero value of string type in Golang.

Should it be fixed as follows?

```go
if request.Hybrid.Embedder != "" {
  hybrid["embedder"] = request.Hybrid.Embedder
}
```

**Expected behavior**

![image](https://github.com/meilisearch/meilisearch-go/assets/96157/03fcae40-cebf-43a7-a6f4-cf7e67c48583)

I expected that omitting `Embedder` selects the `"default"` embedder as document says.

**Current behavior**

The SDK sends `""` to the server and it responds with the following error:

> ```
> Cannot find embedder with name ``.
> Code: invalid_embedder
> Type: invalid_request
> Link: https://docs.meilisearch.com/errors#invalid_embedder (path "POST /indexes/CatalogItems/search" with method "Search")
> ```

**Environment (please complete the following information):**
- OS: Debian GNU/Linux
- Meilisearch version: v0.18.1
- meilisearch-go version: v0.26.3

**Comment by curquiza** [comment]
Thanks @yuku for the report

Any PR are welcome ❤️
