### ISSUE TITLE
Choice value or pointer receiver on Index type

### ISSUE THREAD

**Issue by Ja7ad** [meilisearch/meilisearch-go#553]
**Description**
In some methods we use value receiver and some methods used pointer receiver, Base on Go documentation we need choice one way.

Best practice is use pointer receiver.

https://go.dev/tour/methods/8

**Screenshots or Logs**

https://github.com/meilisearch/meilisearch-go/blob/869e74304eae91d70de5a9ac814c55b4683f33c4/index_documents.go#L209

https://github.com/meilisearch/meilisearch-go/blob/869e74304eae91d70de5a9ac814c55b4683f33c4/index_documents.go#L155

**Comment by curquiza** [comment]
Hello @Ja7ad 
Thanks for this suggestion!

**Comment by Ja7ad** [comment]
@curquiza This issue fixed on refactor.
