### ISSUE TITLE
Support retry pattern on status code 502, 503, 504

### ISSUE THREAD

**Issue by Ja7ad** [meilisearch/meilisearch-go#569]
**Description**
The current implementation lacks built-in support for a retry mechanism when encountering certain transient server errors, specifically HTTP status codes 502 (Bad Gateway), 503 (Service Unavailable), and 504 (Gateway Timeout). These status codes often indicate temporary issues that may resolve on a subsequent request, making a retry pattern beneficial for improving the resilience of the application.

Adding support for automatic retries when these status codes are returned would help ensure that temporary server-side issues do not result in unnecessary request failures, thus enhancing the robustness and reliability of the client application.

**Basic example**
The retry logic could be implemented in a way similar to the following example. If a request returns a status code of 502, 503, or 504, the client should automatically retry the request after a short delay. The number of retry attempts and the delay between attempts could be configurable.

```go
// Example implementation of a retry pattern for status codes 502, 503, 504.
resp, err := client.Do(request)
if err != nil {
    // Handle error
}
retryCount := 0
maxRetries := 3
for retryCount < maxRetries && (resp.StatusCode == 502 || resp.StatusCode == 503 || resp.StatusCode == 504) {
    retryCount++
    time.Sleep(time.Second * 2) // Delay between retries
    resp, err = client.Do(request)
    if err != nil {
        // Handle error
    }
}
```

**Other**
- Consider adding exponential backoff or jitter to the retry logic to prevent overwhelming the server with requests in a short time span.
- Ensure that the retry mechanism is easily configurable, allowing developers to specify custom retry logic if needed.
- Consider logging each retry attempt for easier debugging and monitoring of retry behavior.

**Note**

This mechanism is optional.

**Comment by curquiza** [comment]
Thanks for the issue @Ja7ad. Seems a nice configuration

Are you using our [Meilisearch cloud offer](https://www.meilisearch.com/cloud)? Are 50X error something you observe often? For how long?

Thanks in advance for your help

**Comment by Ja7ad** [comment]
> Thanks for the issue @Ja7ad. Seems a nice configuration
> 
> Are you using our [Meilisearch cloud offer](https://www.meilisearch.com/cloud)? Are 50X error something you observe often? For how long?
> 
> Thanks in advance for your help

This is an option for client and help to be self-hosted.
