### ISSUE TITLE
Using SearchRequest.FacetsDistribution creates invalid request

### ISSUE THREAD

**Issue by mikemrm** [meilisearch/meilisearch-go#62]
Hello,

I'm running into an issue with adding `FacetsDistribution` to my `SearchRequest` object. It appears a change made recently is generating an invalid value.

I'm running go `1.13.6` on linux, pulling from master. Though it seems the following change has been implemented for all of `0.11.x`.

https://github.com/meilisearch/meilisearch-go/blob/e80b241566648d8da4a3608e28df548ccae4fba8/client_search.go#L56

The problem seems to be `%q` is escaping the prequoted list, resulting in an empty `FacetsDistribution` in the response.

Example usage:
```golang
facets := []string{"city", "state"}
results, _ :=client.Search(idx).Search(meilisearch.SearchRequest{
	Query: "bob",
	FacetsDistribution: facets,
})
// results.FacetsDistribution is empty
```

The problem can be replicated with
```golang
facets := []string{"city", "state"}
fmt.Printf("[%q]", strings.Join(facets, "\",\""))
// Result: ["city\",\"state"]
```
https://play.golang.org/p/Gh2USjlJvsG

Thanks!

**Comment by eskombro** [comment]
This issue has been solved some time ago, I forgot to close it! Don't hesitate to reopen if any other problem comes up!
