### ISSUE TITLE
Searchable Attributes not persisting 

### ISSUE THREAD

**Issue by hi019** [meilisearch/meilisearch-go#77]
Hi, I'm having an issue with `UpdateSearchableAttributes` not saving after a document insert. To reproduce:
1. Create new directory, then run `go mod init` and `go get github.com/meilisearch/meilisearch-go`
2. Paste code below
3. Start Meilisearch 
4. `go run main.go`, you should see `[Name]` printed. That is the searchable attribute. 
5. Comment out line 42 (`createIndex()` in main)  and run again
6. You should see `[Name Year]` printed, meaning the settings created in `createIndex` were not persisted. 

<details>
<summary>Code</summary>

```
package main

import (
	"fmt"
	"time"

	"github.com/meilisearch/meilisearch-go"
)

type Movie struct {
	Name string
	Year int
	ID   int
}

var uid = "movies4"

var client = meilisearch.NewClient(meilisearch.Config{
	Host: "http://127.0.0.1:7700",
})

func createIndex() {
	// Create index
	client.Indexes().Create(meilisearch.CreateIndexRequest{
		UID:        uid,
		PrimaryKey: "ID",
	})

	// Update searchable attirbutes
	_, err := client.Settings(uid).UpdateSearchableAttributes([]string{"Name"})
	if err != nil {
		fmt.Println(err)
	}

	time.Sleep(time.Second)
}

func insert(id int) {
	// Insert document
	movies := []Movie{Movie{Name: "The Shining", Year: 1980, ID: id}}
	_, err := client.Documents(uid).AddOrUpdate(&movies)
	if err != nil {
		fmt.Println(err)
	}

	// Get searchable attributes
	a, err := client.Settings(uid).GetSearchableAttributes()
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(*a)
}

func main() {
	createIndex()
	insert(1)
}


``` 
</details>

**Comment by hi019** [comment]
Related? meilisearch/MeiliSearch/issues/942

**Comment by curquiza** [comment]
Hello @hi019!

I was able to reproduce your issue with MeiliSearch v0.14.0 by only using `curl` and the MeiliSearch API.
It's indeed related to this issue you mentioned! 🙂

Thanks for the report, I close this issue in favor of meilisearch/MeiliSearch/issues/942
