### ISSUE TITLE
Delete indexes after tests

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#8]
Currently, if I have already a MeiliSearch isntance running locally, and if I run the tests `./run_tests.sh`, there are several indexes still running in my MeiliSearch instance.

We should provide tests that clean all the indexes created for tests purpose.

**Comment by alexisvisco** [comment]
The docker command to launch the Meilisearch has  a ` --rm` flag so there is no remaining container after the tests.

**Comment by curquiza** [comment]
As I said, I already had a local MeiliSearch instance for dev purposes when I ran the tests. In this case, the script test uses the current running MeiliSearch instance instead of running a new one in a docker. So, my local instance was full of test indexes after that.
It's not a big issue, but it's not really convenient to dev with this kind of behavior ;)

I re-open the issue because I want it to be fixed.

**Comment by eskombro** [comment]
The docker image has the rm command, that is true. But there are still two valid arguments for this in my opinion:

- The tests are not always run with the shell script. You can use plugins to test automatically, or run test partially from console, etc... use different CI tools... so even if it is a good thing to create a docker container and test inside, and then delete the container, we shouldn't rely on the shell script as a guaranty.

- Every test must be as independent as possible. It should also clean any modification done to the MeiliSearch instance afterwards, to avoid interfering with any other tests, running applications, etc. It should be as atomic and isolated as possible IMHO.
