### ISSUE TITLE
Implement dumps (add tests and code samples)

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-go#82]
Since [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0), MeiliSearch exposes a new functionality: [dumps](https://docs.meilisearch.com/references/dump.html#dumps)

This feature should be implemented in this SDK following [this specificacions](https://github.com/meilisearch/integration-guides/issues/44)

- [x] Implement dump creation route
- [x] Implement get dump status route
- [x] Add tests
- [x] Add code samples

**Comment by claudiunicolaa** [comment]
hi @eskombro 

is there anything more to do on this issue? happy to add if smth needed.

**Comment by eskombro** [comment]
Thanks @claudiunicolaa 

All work is done here, we forgot to close, but routes are implemented, tests and samples are done!
