### ISSUE TITLE
Make sdk faster

### ISSUE THREAD

**Issue by senyast4745** [meilisearch/meilisearch-go#86]
As I think **http/client** is a rather slow library. I would like to use something faster as the httpclient, for example the [fasthttpclient](https://github.com/valyala/fasthttp). It also probably makes sense to add methods for sending requests with a raw body ([] byte). I can take it on myself

**Comment by eskombro** [comment]
Hi @senyast4745!

Thanks a lot, this would be a very great improvement, benchmarks seem promising! 🎉

**Comment by senyast4745** [comment]
Hi @eskombro!
Thank you very much for your reply. Then can you assign this issue?

**Comment by curquiza** [comment]
done @senyast4745 😉

**Comment by senyast4745** [comment]
Thanks. Only I had a problem. FastHttp is not compatible with standard http / client and this required some pretty drastic changes in the sdk design. I also used easyjson and fastjson to speed up serialization / deserialization, which also led to quite strong changes in the API

**Comment by senyast4745** [comment]
@curquiza  Oops. I accidentally pressed the unassign button. Could you assign me again?
