### ISSUE TITLE
golint

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-go#9]
In the development workflow part there is two points about golint:
```bash
# Install golint
$ go get -u golang.org/x/lint/golint
# Use golint
$ golint
```

2 issues:
- The first command modifies the `go.sum` and the `go.mod` files. Is it expected?
- Despite I ran the first command, the `golint` tool is still unavailable for me. 

When I run `go get -u golang.org/x/lint/golint` I get:
```bash
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: golang.org/x/tools upgrade => v0.0.0-20200325010219-a49f79bcc224
```
And the command returns 0 (success).

**Comment by curquiza** [comment]
This issue is still there, I don't know how to fix that 😅 Please, help!

**Comment by eskombro** [comment]
1. When you do `go get -u ...` you are telling your system to upgrade that module. But if you are working in some project directory, it will update it also as a dependency for the project you are working on. As you update your dependencies, it is normal that it changes your `go.mod` which has the requirements for your project, and your `go.sum` which contains hashes for the modules it depends on. If you change your working directory and do `go get -u ...` it wont update it in your project dependencies.

2. Installing golint doesn't necessarily make the binary available in your system PATH, so the command mey not be available directly. All the go binaries from external modules are usually located at `<home>/go/bin` or if you defined a GOPATH environment variable, in the path that variable is pointing to you will find a `bin` directory. You can add it to your path.

In the golint docs, they say:

```
To find out where golint was installed you can run go list -f {{.Target}} golang.org/x/lint/golint. For golint to be used globally add that directory to the $PATH environment setting.
```

**Comment by curquiza** [comment]
Thanks @eskombro! I can finally realize the package has linter errors on `master` now 😂!!!
Fixing that...
