### ISSUE TITLE
Document how to update EasyJson file in CONTRIBUTING.md

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-go#90]
#88 introduced [EasyJson](https://github.com/mailru/easyjson) to this repo. It autogenerates a file `types_easyjson.go` by using the command 

```bash
easyjson -all types.go
```

This should be documented in the CONTRIBUTING.md

More info at https://github.com/mailru/easyjson#usage

**Comment by eskombro** [comment]
@senyast4745 Would you be up for this maybe? :)

**Comment by senyast4745** [comment]
@eskombro The correct command with which I generated the easyjson file is as follows.

```sh
easyjson -all types.go
```

**Comment by eskombro** [comment]
Sorry, my bad! Fixed in the description 🚀

**Comment by senyast4745** [comment]
@eskombro can you document it in into **CONTRIBUTING.md**?

**Comment by senyast4745** [comment]
Or if you want I can do it

**Comment by senyast4745** [comment]
I think it's no so hard issue))

**Comment by eskombro** [comment]
Of course, it isn't hard 😉 I created this issue so we don't forget to do it !
I wanted to ask you as you introduced it, maybe you would prefer to document it! But I can do it quickly :)

**Comment by eskombro** [comment]
Can you check it out @senyast4745 ? Thanks !
