### ISSUE TITLE
Module name changed from meilisearch/meilisearch to senyast4745/meilisearch

### ISSUE THREAD

**Issue by lacroixsteven** [meilisearch/meilisearch-go#95]
Hello, I can't import this module. It looks like the module name was change from meilisearch/meilisearch to senyast4745/meilisearch

`
go: github.com/meilisearch/meilisearch-go: github.com/meilisearch/meilisearch-go@v0.13.0: parsing go.mod:
        module declares its path as: github.com/senyast4745/meilisearch-go
                but was required as: github.com/meilisearch/meilisearch-go
`

Thanks

**Comment by curquiza** [comment]
Hello @lacroixsteven!
Thanks for this report! I created a PR. It will be merged today and also I will create a new release today!
Sorry about this!

**Comment by curquiza** [comment]
The v0.13.1 is out 🙂
